apiVersion: missioncontrol.datastax.com/v1beta2
kind: MissionControlCluster
metadata:
  name: hcd
  namespace: dambor-763us52d
spec:
  dataApi:
      enabled: true
      port: 8181
  createIssuer: true
  encryption:
    internodeEncryption:
      certs:
        certTemplate:
          issuerRef:
            name: ""
          secretName: ""
        createCerts: true
      enabled: true
    managementApiAuthEncryption:
      certs:
        certTemplate:
          issuerRef:
            name: ""
          secretName: ""
        createCerts: true
      enabled: true
  k8ssandra:
    auth: true
    cassandra:
      containers:
      - env:
        - name: DSE_AUTO_CONF_OFF
          value: all
        - name: DSE_MGMT_EXPLICIT_START
          value: "true"
        name: cassandra
        resources: {}
      datacenters:
      - datacenterName: gcp
        metadata:
          name: hcd-gcp
          pods: {}
          services:
            additionalSeedService: {}
            allPodsService: {}
            dcService: {}
            nodePortService: {}
            seedService: {}
        perNodeConfigInitContainerImage: mikefarah/yq:4
        perNodeConfigMapRef: {}
        racks:
        - name: rack1
          nodeAffinityLabels:
            mission-control.datastax.com/role: database
        - name: rack2
          nodeAffinityLabels:
            mission-control.datastax.com/role: database
        - name: rack3
          nodeAffinityLabels:
            mission-control.datastax.com/role: database
        size: 3
        stopped: false
        storageConfig:
          cassandraDataVolumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Ti
            storageClassName: premium-rwo
      metadata:
        pods: {}
        services:
          additionalSeedService: {}
          allPodsService: {}
          dcService: {}
          nodePortService: {}
          seedService: {}
      networking:
        hostNetwork: false
      perNodeConfigInitContainerImage: mikefarah/yq:4
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
      serverType: hcd
      serverVersion: 1.1.0
      superuserSecretRef: {}
    secretsProvider: internal
