apiVersion: k8ssandra.io/v1beta1
kind: K8ssandraCluster
metadata:
  name: hcd-gcp
  namespace: mission-control
spec:
  cassandra:
    serverVersion: "4.0.11"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    config:
      jvmOptions:
        heapSize: 512M
    networking:
      hostNetwork: false
    datacenters:
      - metadata:
          name: gcp
        size: 3
        racks:
          - name: rack1
          - name: rack2
          - name: rack3
        stargate:
          size: 1
          heapSize: 256M
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  reaper:
    deploymentMode: SIDECAR
